### ISSUE TITLE
BUG: Creating a new account on the app does not work

### ISSUE THREAD

**Issue by darewealth** [AndreMiras/EtherollApp#133]
### Describe the Bug:
When I click on the wallet button to create an account on the app. I input my new password to create a new account, it brings information that an account is creating but nothing seems to be created.

### To Reproduce:
Launch the app

Click the menu icon

Go to the wallet, input your password and create account

### Expected Behavior:
I expected that I should be able to create an account on the app. 

### Recording Of The Bug
https://youtu.be/ukf-1dIyz28

### Devices and Versions):)
Device: [Itel]

Version [6.1]

App version [2019.0217 (202117)]

**Comment by AndreMiras** [comment]
Thank you for the descriptive bug report. Yes that's annoying, it's probably a case of #131 a permission issue and it was solved in a recent release.
I guess you installed via F-Droid, did you? F-Droid didn't pick up the update yet. Could you try again installing the last release https://github.com/AndreMiras/EtherollApp/releases/download/v20190418/etheroll-2019.0418-debug.apk ?
Otherwise you can wait for the update to be published on F-Droid, I'm currently working on that via https://gitlab.com/fdroid/fdroiddata/merge_requests/4768

**Comment by darewealth** [comment]
I have updated the app with the current build, but the issue persists. Check the video I added.

https://youtu.be/wYbbwBLFjd8

**Comment by AndreMiras** [comment]
Thanks for trying it out and thanks for the video, it's very helpful.
I'm wondering if this is related to another upstream bug I've seen in Kivy in the past.
It had to do with the `/sdcard` folder not existing on some devices. Does your device have a sdcard plugged in? Can you by any chance try on another device?
In the meantime I'll try to make a dedicated release to catch this error not silently. Because if it's indeed the issue I'm thinking of now, it just fail in the background without saying anything.
In case you need direct chat, I'm also on Etheroll discord, feel free to ping me:
https://discord.gg/bb6Qjt
So I'll try first to catch the error non-silently to make sure that's the one and keep you posted.

**Comment by AndreMiras** [comment]
Great @darewealth I think found a way to reproduce it. I hope to be able to fix by the beginning of next week. I'll keep you posted.

**Comment by darewealth** [comment]
Thank you. I would be expecting the fix. I also have another issue. I will open another issue page for it.

**Comment by AndreMiras** [comment]
I've worked on an [early fix](https://github.com/AndreMiras/EtherollApp/commit/c2f62b700f113537163603e5bd91cacf087724a3) I've uploaded an APK if you want to give it a try:
https://github.com/AndreMiras/EtherollApp/releases/download/v20190418-debug-133/etheroll-2019.0418-debug-issue-133.apk

It's still in a draft status, but let's see if it helps. Could you give it a try and let me know if it works better for you?

**Comment by AndreMiras** [comment]
The fix seems solid, so I've made a release with it, could you give it a try?
https://github.com/AndreMiras/EtherollApp/releases/download/v2019.0426/etheroll-2019.0426-debug.apk

**Comment by darewealth** [comment]
Everything is now working perfectly. :+1:

**Comment by AndreMiras** [comment]
Sentry issue: [ETHEROLL-BE-21](https://sentry.io/organizations/andre-5t/issues/1000520213/?project=1111738&referrer=github_plugin)

**Comment by AndreMiras** [comment]
Sentry issue: [ETHEROLL-BE-1Y](https://sentry.io/organizations/andre-5t/issues/994194867/?project=1111738&referrer=github_plugin)

**Comment by AndreMiras** [comment]
Sentry issue: [ETHEROLL-BE-20](https://sentry.io/organizations/andre-5t/issues/994298638/?project=1111738&referrer=github_plugin)

**Comment by AndreMiras** [comment]
Sentry issue: [ETHEROLL-BE-25](https://sentry.io/organizations/andre-5t/issues/1001550961/?project=1111738&referrer=github_plugin)
